version: "3.9"
services:
  server:
    build: ./app
    ports:
    - "8080:8080"
    volumes:
    - .:/case_apps.db
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - server