version: "3.9"
services:
  server:
    build: ./app
    ports:
    - "8080:8080"
    environment:
      - SQLITE_PATH=/case_apps.db
    volumes:
    - .:/case_apps.db
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/case_apps.db
    depends_on:
      - server